### ISSUE TITLE
[Bug] t.sentinel.import: UnboundLocalError: local variable 'filepath' referenced before assignment

### ISSUE THREAD

**Issue by neteler** [mundialis/t.sentinel#12]
I tried to use the `-a` flag but it leads to an error:

```
GRASS nc_spm_08_grass7/sentinel2 > t.sentinel.import nprocs=8 pattern='B(02_10|03_10|04_10|08_10)m' \
    strds_output=s2_raleigh input_dir=~/tmp/s2_data/ memory=6000 -a sen2cor_path=~/Sen2Cor-02.08.00-Linux64/

Starting atmospheric correction with sen2cor...
Traceback (most recent call last):
  File "/home/mneteler/.grass8/addons/scripts/t.sentinel.import", line 548, in <module>
    main()
  File "/home/mneteler/.grass8/addons/scripts/t.sentinel.import", line 396, in main
    input_file=filepath,
UnboundLocalError: local variable 'filepath' referenced before assignment
```

**Comment by griembauer** [comment]
Thanks for finding this - can you show the structure of `~/tmp/s2_data/`? If `input_dir` is used, it is expected to contain the Sentinel-2 scenes in `.SAFE`-format. This does not seem to be the case here. In any case, a proper error message would be helpful.

**Comment by neteler** [comment]
This is the dir structure:

```
~/tmp/s2_data$ tree
.
├── download_762418
└── download_763787
    ├── dl_s2_1
    │   └── S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.zip
    ├── dl_s2_2
    │   └── S2B_MSIL2A_20210513T155819_N0300_R097_T17SPV_20210513T195734.zip
    ├── dl_s2_3
    │   └── S2A_MSIL2A_20210515T154911_N0300_R054_T17SPV_20210515T201322.zip
    └── dl_s2_4
        └── S2A_MSIL2A_20210515T154911_N0300_R054_T17SQV_20210515T201322.zip

```

**Comment by neteler** [comment]
Importantly, I had then re-arranged the files from the original structure after download to this one (assuming, that import from existing directory needs all files in one...):

```
mneteler@caddy: ~/tmp/s2_data$ mv download_763787/dl_s2_*/S* .
mneteler@caddy: ~/tmp/s2_data$ l
total 3327420
-rw-rw-r-- 1 mneteler mneteler  868794774 May 25 13:24 S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.zip
-rw-rw-r-- 1 mneteler mneteler 1182735111 May 25 13:30 S2B_MSIL2A_20210513T155819_N0300_R097_T17SPV_20210513T195734.zip
drwxrwxr-x 6 mneteler mneteler         66 May 25 13:30 download_763787/
-rw-rw-r-- 1 mneteler mneteler  176974758 May 25 13:32 S2A_MSIL2A_20210515T154911_N0300_R054_T17SPV_20210515T201322.zip
-rw-rw-r-- 1 mneteler mneteler 1178765084 May 25 13:40 S2A_MSIL2A_20210515T154911_N0300_R054_T17SQV_20210515T201322.zip

mneteler@caddy: ~/tmp/s2_data$ rmdir download_763787/dl_s2_*
mneteler@caddy: ~/tmp/s2_data$ rmdir download_763787
mneteler@caddy: ~/tmp/s2_data$ l
total 3327420
-rw-rw-r-- 1 mneteler mneteler  868794774 May 25 13:24 S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.zip
-rw-rw-r-- 1 mneteler mneteler 1182735111 May 25 13:30 S2B_MSIL2A_20210513T155819_N0300_R097_T17SPV_20210513T195734.zip
-rw-rw-r-- 1 mneteler mneteler  176974758 May 25 13:32 S2A_MSIL2A_20210515T154911_N0300_R054_T17SPV_20210515T201322.zip
-rw-rw-r-- 1 mneteler mneteler 1178765084 May 25 13:40 S2A_MSIL2A_20210515T154911_N0300_R054_T17SQV_20210515T201322.zip
```

Not sure if that interfered? However, the ZIP type nature remained the same.

**Comment by griembauer** [comment]
Thank you. Here it would be helpful to define an "expected behaviour" on how `input_dir` should be structured.

- An additional flag to indicate whether the scenes in `input_dir` are in separate directories themselves (e.g. `dl_s2_*`)?
- Which formats should be supported? .SAFE vs. .zip? Where do the .zip files actually come from in your example (i.e. why are they not .SAFE)?

**Comment by neteler** [comment]
The ZIP file content is as follows:

```
unzip -l S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.zip | head
Archive:  S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    52858  05-23-2021 23:38   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/MTD_MSIL2A.xml
    91867  05-23-2021 23:39   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/manifest.safe
    18798  05-23-2021 23:38   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/INSPIRE.xml
        0  01-01-1980 00:00   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/AUX_DATA/
   375177  05-23-2021 23:38   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/GRANULE/L2A_T17SQV_A022002_20210523T161112/MTD_TL.xml
      810  05-23-2021 23:34   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/GRANULE/L2A_T17SQV_A022002_20210523T161112/AUX_DATA/AUX_ECMWFT
      428  05-23-2021 23:35   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/GRANULE/L2A_T17SQV_A022002_20210523T161112/QI_DATA/MSK_SATURA_B09.gml
...
CORRECTNESS.xml
     7451  05-23-2021 23:38   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/DATASTRIP/DS_VGS2_20210523T202619_S20210523T161112/QI_DATA/GEOMETRIC_QUALITY.xml
     4187  05-23-2021 23:38   S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.SAFE/DATASTRIP/DS_VGS2_20210523T202619_S20210523T161112/QI_DATA/SENSOR_QUALITY.xml
---------                     -------
868748636                     132 files

```

**Comment by neteler** [comment]
I tried from scratch (download from ESA), still...:

```
GRASS nc_spm_08_grass7/sentinel2:~ > tree tmp/s2_data/
tmp/s2_data/
└── download_836915
    ├── dl_s2_1
    │   └── S2B_MSIL2A_20210523T155819_N0300_R097_T17SQV_20210523T202619.zip
    ├── dl_s2_2
    │   └── S2A_MSIL2A_20210515T154911_N0300_R054_T17SPV_20210515T201322.zip
    ├── dl_s2_3
    │   └── S2B_MSIL2A_20210513T155819_N0300_R097_T17SPV_20210513T195734.zip
    └── dl_s2_4
        └── S2A_MSIL2A_20210515T154911_N0300_R054_T17SQV_20210515T201322.zip

5 directories, 4 files
GRASS nc_spm_08_grass7/sentinel2:~ > t.sentinel.import nprocs=8 pattern='B(02_10|03_10|04_10|08_10)m' strds_output=s2_raleigh input_dir=~/tmp/s2_data/ memory=6000 -a sen2cor_path=~/Sen2Cor-02.08.00-Linux64/ --o 
Starting atmospheric correction with sen2cor...
Traceback (most recent call last):
  File "/home/mneteler/.grass8/addons/scripts/t.sentinel.import", line 561, in <module>
    main()
  File "/home/mneteler/.grass8/addons/scripts/t.sentinel.import", line 396, in main
    input_file=filepath,
UnboundLocalError: local variable 'filepath' referenced before assignment
```

**Comment by mmacata** [comment]
@neteler is this still relevant?

**Comment by neteler** [comment]
As I cannot test this at time I assume it to be solved (no related reports came up). Closing for now.
