### ISSUE TITLE
t.sentinel.import: ESA_COAH: HTTP status 429 Too Many Requests when data already downloaded

### ISSUE THREAD

**Issue by neteler** [mundialis/t.sentinel#4]
In [days of ESA Hub maintenance](https://scihub.copernicus.eu/news/News00829) often a "429 Too Many Requests" appears.

If possible, please catch this error to avoid the long "Traceback":

```
GRASS utm32N_25832/wilhelmshaven:~ > t.sentinel.import settings=~/.sentinel_esa s2names=s2names.txt nprocs=4   pattern='B(02_10|03_10|04_10|08_10)m' strds_output=s2_${AREA} directory=~/tmp/s2_data/
Downloading Sentinel scenes ...
ERROR: Unable to connect to ESA_COAH: HTTP status 429 Too Many Requests: 
# 429 Too Many Requests

You have sent too many requests in a given amount of time.
Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/i.sentinel.parallel.download", line 280, in <module>
    sys.exit(main())
  File "/home/mneteler/.grass7/addons/scripts/i.sentinel.parallel.download", line 275, in main
    queue_download.wait()
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/modules/interface/module.py", line 314, in wait
    proc.wait(),
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/modules/interface/module.py", line 839, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run i.sentinel.download i.sentinel.download settings=/home/mneteler/.sentinel_esa output=/home/mneteler/tmp/s2_data/dl_s2_3 area_relation=Intersects producttype=S2MSI2A start=2020-08-14 end=2020-08-16 query=filename=S2A_MSIL2A_20200815T104031_N0214_R008_T32UME_20200815T115046.SAFE retry=5 datasource=ESA_COAH sort=cloudcoverpercentage,ingestiondate,footprint order=asc ended with error
Process ended with non-zero return code 1. See errors in the (error) output.
Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/t.sentinel.import", line 374, in <module>
    main()
  File "/home/mneteler/.grass7/addons/scripts/t.sentinel.import", line 233, in main
    grass.run_command(
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 543, in run_command
    return handle_errors(returncode, result=None, args=args, kwargs=kwargs)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 428, in handle_errors
    raise CalledModuleError(module=module, code=code, returncode=returncode)
grass.exceptions.CalledModuleError: Module run i.sentinel.parallel.download i.sentinel.parallel.download --q -fs settings=/home/mneteler/.sentinel_esa scene_name=S2A_MSIL2A_20200914T104031_N0214_R008_T32UME_20200914T133417,S2A_MSIL2A_20200921T103031_N0214_R108_T32UME_20200921T151006,S2A_MSIL2A_20200815T104031_N0214_R008_T32UME_20200815T115046 nprocs=4 output=/home/mneteler/tmp/s2_data/ ended with error
Process ended with non-zero return code 1. See errors in the (error) output.

```

**Comment by neteler** [comment]
I checked further, it seems that the error message is misleading.

My data request:

```
GRASS utm32N_25832/wilhelmshaven:~ >
cat s2names.txt
S2A_MSIL2A_20200914T104031_N0214_R008_T32UME_20200914T133417,S2A_MSIL2A_20200921T103031_N0214_R108_T32UME_20200921T151006,S2A_MSIL2A_20200815T104031_N0214_R008_T32UME_20200815T115046
```

Indeed, the data were already downloaded earlier today! I had re-run this module several times and only now checked the output directory:

```
tree /home/mneteler/tmp/s2_data/
/home/mneteler/tmp/s2_data/
├── dl_s2_1
│   └── S2A_MSIL2A_20200914T104031_N0214_R008_T32UME_20200914T133417.zip
├── dl_s2_2
│   └── S2A_MSIL2A_20200921T103031_N0214_R108_T32UME_20200921T151006.zip
├── dl_s2_3
│   └── S2A_MSIL2A_20200815T104031_N0214_R008_T32UME_20200815T115046.zip
```

Hence I have the impression that "429 Too Many Requests" is triggered because the data are already there and the loop over the requested data runs too fast, leading to too many requests in a short time at ESA.

If true, then `t.sentinel.import` should not attempt to download at all when the Sentinel data are already locally present.

**Comment by neteler** [comment]
In fact, when commenting out `i.sentinel.parallel.download` in `t.sentinel.import` the import works since the data are there...

**Comment by griembauer** [comment]
In https://github.com/mundialis/t.sentinel/pull/3 a new download-directory is added within `directory`. This means data will always be downloaded first, and this issue should not occur because already downloaded data will not be found. Deleting the download-directory at the end of `t.sentinel.import `could also be implemented to leave a clean environment.
Is it a re-occuring use case to rely on data that is already stored locally?

**Comment by neteler** [comment]
> Is it a re-occuring use case to rely on data that is already stored locally?

In my view yes, download of a larger amount of scenes may have been interrupted to do USGS server unreachable, local disk full or other reasons and one may want to continue with downloading rather than starting over...

**Comment by mmacata** [comment]
@neteler is this still relevant?
